apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-gdrive
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: rclone-gdrive
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: rclone.conf
      remoteRef:
        key: rclone-gdrive
        property: rclone_conf
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
