apiVersion: v1
kind: Namespace
metadata:
  name: jdwlabs-runners
  labels:
    platform.jdwlabs.io/tenant: jdwlabs
    platform.jdwlabs.io/type: ci
---
apiVersion: v1
kind: Namespace
metadata:
  name: dotablaze-tech-runners
  labels:
    platform.jdwlabs.io/tenant: dotablaze-tech
    platform.jdwlabs.io/type: ci
