apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-scale-set-controller-secrets
  namespace: jdwlabs-runners
subjects:
  - kind: ServiceAccount
    name: arc-systems-gha-rs-controller
    namespace: arc-systems
roleRef:
  kind: Role
  name: gha-runner-scale-set-controller-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-scale-set-controller-secrets
  namespace: dotablaze-tech-runners
subjects:
  - kind: ServiceAccount
    name: arc-systems-gha-rs-controller
    namespace: arc-systems
roleRef:
  kind: Role
  name: gha-runner-scale-set-controller-secrets
  apiGroup: rbac.authorization.k8s.io
