apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: jdwlabs-atlas-schema-non
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  credentials:
    scheme: postgres
    host: platform-postgresql-cluster-non-rw.database.svc
    user: jdwlabs_non_owner
    passwordFrom:
      secretKeyRef:
        key: password
        name: jdwlabs-non-owner-credentials
    database: jdwlabs_non
    port: 5432
    parameters:
      sslmode: disable
  schema:
    configMapKeyRef:
      key: schema.sql
      name: jdwlabs-postgresql-non-schema
