apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-jdwlabs-non
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flyway
          image: flyway/flyway:11.2
          env:
            - name: FLYWAY_URL
              value: "jdbc:postresql://platform-postgresql-cluster-non-rw.database.svc:5432/jdwlabs_non"
            - name: FLYWAY_USER
              value: app
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: platform-postgresql-cluster-non-app
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "0"
            - name: FLYWAY_DEFAULT_SCHEMA
              value: public
            - name: FLYWAY_SCHEMAS
              value: public,auth
          args:
            - "-locations=filesystem:/flyway/sql"
            - "migrate"
          volumeMounts:
            - mountPath: /flyway/sql
              name: migrations
      volumes:
        - name: migrations
          configMap:
            name: jdwlabs-migrations
