apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
data:
  console_websocket_password: Y2hhbmdlbWU=
  console_password: Y2hhbmdlbWU=
  bridge_token: Y2hhbmdlbWU=
