nginxGateway:
  kind: deployment
  replicas: 2
  snippets:
    enable: true
  config:
    logging:
      level: info
  metrics:
    enable: true
    port: 9113

nginx:
  kind: daemonSet
  config:
    ipFamily: ipv4
    rewriteClientIP:
      mode: ProxyProtocol
      setIPRecursively: true
      trustedAddresses:
        - type: CIDR
          value: 0.0.0.0/0
  service:
    type: NodePort
    nodePorts:
      - port: 30180
        listenerPort: 80
      - port: 30543
        listenerPort: 443

gateways:
  - name: platform-gateway
    namespace: nginx-gateway
    spec:
      gatewayClassName: nginx
      listeners:
        - name: http
          port: 80
          protocol: HTTP
          allowedRoutes:
            namespaces:
              from: All
        - name: https
          port: 443
          protocol: HTTPS
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                name: wildcard-jdwlabs-tls
          allowedRoutes:
            namespaces:
              from: All
