apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-basic-auth
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: alertmanager-basic-auth
    template:
      type: nginx.org/htpasswd
      data:
        auth: "{{ .auth }}"
  data:
    - secretKey: auth
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: alertmanager
        property: htpasswd_string
