{{- range .Values.namespaces }}
{{- if .arc }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-runner-scale-set-controller-secrets
  namespace: {{ .name }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["actions.github.com"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-scale-set-controller-secrets
  namespace: {{ .name }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values._arc.controllerServiceAccount.name }}
    namespace: {{ $.Values._arc.controllerServiceAccount.namespace }}
roleRef:
  kind: Role
  name: gha-runner-scale-set-controller-secrets
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
