{{- if .Values.deploymentRepo.url }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}-deployments
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - git:
              repoURL: {{ .Values.deploymentRepo.url | quote }}
              revision: {{ .Values.deploymentRepo.revision | quote }}
              files:
                - path: argocd/*/config.yaml
          - list:
              elementsYaml: '{{ "{{" }} .apps | toJson {{ "}}" }}'
  template:
    metadata:
      name: '{{ .Values.name }}-{{ "{{" }} .name {{ "}}" }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ "{{" }} .syncWave | default "0" | toString {{ "}}" }}'
    spec:
      project: tenant-{{ .Values.name }}
      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jqPathExpressions:
            - .spec.persistentVolumeClaimRetentionPolicy
            - .spec.podManagementPolicy
            - .spec.updateStrategy
            - .spec.template.metadata.annotations
            - .spec.volumeClaimTemplates[]?.apiVersion
            - .spec.volumeClaimTemplates[]?.kind
            - .spec.volumeClaimTemplates[]?.spec.volumeMode
            - .spec.volumeClaimTemplates[]?.status
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - .spec.template.metadata.annotations."checksum/secret"
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          jqPathExpressions:
            - .spec.parentRefs[]?.group
            - .spec.parentRefs[]?.kind
            - .spec.rules[]?.backendRefs[]?.group
            - .spec.rules[]?.backendRefs[]?.kind
            - .spec.rules[]?.backendRefs[]?.weight
            - .spec.rules[]?.matches
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      destination:
        namespace: '{{ "{{" }} .namespace {{ "}}" }}'
        server: https://kubernetes.default.svc
  templatePatch: |
    spec:
      sources:
        - repoURL: {{ .Values.deploymentRepo.url | quote }}
          path: '{{ "{{" }} .chartPath {{ "}}" }}'
          targetRevision: {{ .Values.deploymentRepo.revision | quote }}
          helm:
            valueFiles:
              {{ "{{-" }} range .valueFiles {{ "}}" }}
              - {{ "{{" }} . {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
{{- end }}
