{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    platform.jdwlabs.io/tenant: {{ $.Values.name }}
    platform.jdwlabs.io/quota-tier: {{ .quotaTier }}
    {{- if .arc }}
    platform.jdwlabs.io/type: ci
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: restricted
    {{- else if eq .quotaTier "platform" }}
    platform.jdwlabs.io/type: platform
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    {{- else }}
    platform.jdwlabs.io/type: workload
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    {{- end }}
{{- end }}
