{{- range .Values.namespaces }}
{{- if hasKey $.Values._quotaTiers .quotaTier }}
{{- $tier := index $.Values._quotaTiers .quotaTier }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ .name }}
spec:
  hard:
    {{- range $key, $val := $tier }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
{{- end }}
{{- end }}
