{{- if .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.name }}-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=zero"
  generators:
    - list:
        elements: {{ .Values.services | toJson }}
  template:
    metadata:
      name: '{{ .Values.name }}-{{ "{{" }} .name {{ "}}" }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ "{{" }} .syncWave | toString {{ "}}" }}'
    spec:
      project: tenant-{{ .Values.name }}
      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jqPathExpresssions:
            - .spec.persistentVolumeClaimRetentionPolicy
            - .spec.podManagementPolicy
            - .spec.updateStrategy
            - .spec.volumeClaimTemplates[]?.spec.volumeMode
            - .spec.volumeClaimTemplates[]?.status
        - group: apps
          kind: Deployment
          jqPathExpresssions:
            - .spec.template.metadata.annotations."checksum/secret"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      destination:
        namespace: '{{ "{{" }} .namespace {{ "}}" }}'
        server: https://kubernetes.default.svc
  templatePatch: |
    spec:
      sources:
        {{ "{{-" }} if .rawManifests {{ "}}" }}
        - repoURL: {{ .Values._platform.repoURL }}
          targetRevision: {{ .Values._platform.revision }}
          path: tenants/{{ .Values.name }}/services/{{ "{{" }} .name {{ "}}" }}/postInstall
        {{ "{{-" }} else {{ "}}" }}
        {{ "{{-" }} if .chartPath {{ "}}" }}
        - repoURL: '{{ "{{" }} .repo {{ "}}" }}'
          path: '{{ "{{" }} .chartPath {{ "}}" }}'
          targetRevision: '{{ "{{" }} .revision {{ "}}" }}'
          helm:
            valueFiles:
              - $values/tenants/{{ .Values.name }}/services/{{ "{{" }} .name {{ "}}" }}/values.yaml
        {{ "{{-" }} else {{ "}}" }}
        - repoURL: '{{ "{{" }} .repo {{ "}}" }}'
          chart: '{{ "{{" }} .chart {{ "}}" }}'
          targetRevision: '{{ "{{" }} .revision {{ "}}" }}'
          helm:
            valueFiles:
              - $values/tenants/{{ .Values.name }}/services/{{ "{{" }} .name {{ "}}" }}/values.yaml
        {{ "{{-" }} end {{ "}}" }}
        - repoURL: {{ .Values._platform.repoURL }}
          targetRevision: {{ .Values._platform.revision }}
          ref: values
        {{ "{{-" }} if .postInstall {{ "}}" }}
        - repoURL: {{ .Values._platform.repoURL }}
          targetRevision: {{ .Values._platform.revision }}
          path: tenants/{{ .Values.name }}/services/{{ "{{" }} .name {{ "}}" }}/postInstall
        {{ "{{-" }} end {{ "}}" }}
        {{ "{{-" }} end {{ "}}" }}
{{- end }}
