apiVersion: v1
kind: ServiceAccount
metadata:
  name: truenas-csi-controller-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: truenas-csi-node-sa
  namespace: {{ .Release.Namespace }}
