apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: dotablaze-tech-atlas-schema-non
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  credentials:
    scheme: postgres
    host: platform-postgresql-cluster-non-rw.database.svc
    user: postgres
    passwordFrom:
      secretKeyRef:
        key: password
        name: platform-postgresql-cluster-non-superuser
    database: dotablazetech_non
    port: 5432
    parameters:
      sslmode: disable
  schema:
    configMapKeyRef:
      key: schema.sql
      name: dotablaze-tech-postgresql-non-schema
