apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: dotablaze-tech-atlas-schema-prd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  credentials:
    scheme: postgres
    host: platform-postgresql-cluster-prd-rw.database.svc
    user: dotablaze_prd_owner
    passwordFrom:
      secretKeyRef:
        key: password
        name: dotablazetech-prd-owner-credentials
    database: dotablazetech_prd
    port: 5432
    parameters:
      sslmode: disable
  schema:
    configMapKeyRef:
      key: schema.sql
      name: dotablaze-tech-postgresql-prd-schema
