run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: true
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
