extends: default
ignore: |
  bootstrap/crds/foundation-crds.yaml
  tenants/platform/services/*/postInstall/dashboard-*.yaml
rules:
  line-length:
    max: 300
  truthy:
    allowed-values: ['true', 'false']
  comments:
    min-spaces-from-content: 1
  document-start: disable
