apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
stringData:
  console_websocket_password: "placeholder-websocket-password"
  console_bridge_token: "placeholder-bridge-token"
