apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
data:
  # Placeholder values; replace with actual secret data from a secure source
  username: bXlfdXNlcm5hbWU=  # base64 of "my_username"
  password: bXlfcGFzc3dvcmQ=  # base64 of "my_password"
