apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-<TENANT>
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: "Tenant <TENANT> applications"
  sourceRepos:
    - 'https://github.com/jdwlabs/platform.git'
    - 'ghcr.io/actions/actions-runner-controller-charts'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '<TENANT>-runners'
    - server: https://kubernetes.default.svc
      namespace: 'database'
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
