apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-basic-auth
  namespace: jdwlabs-ai
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: openclaw-basic-auth
    template:
      type: nginx.org/htpasswd
      data:
        auth: "{{ .auth }}"
  data:
    - secretKey: auth
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: jdwlabs-ai-keys
        property: htpasswd_string
