apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotclasses.snapshot.storage.k8s.io
spec:
  group: snapshot.storage.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                driver:
                  type: string
                deletionPolicy:
                  type: string
                parameters:
                  type: object
                  additionalProperties:
                    type: string
  scope: Namespaced
  names:
    plural: volumesnapshotclasses
    singular: volumesnapshotclass
    kind: VolumeSnapshotClass
    shortNames:
      - volumesnapshotclass
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshots.snapshot.storage.k8s.io
spec:
  group: snapshot.storage.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                volumeSnapshotClassName:
                  type: string
                source:
                  type: object
                  properties:
                    volumeSnapshotContentName:
                      type: string
                    volumeName:
                      type: string
                restoreSize:
                  type: string
            status:
              type: object
              properties:
                boundVolumeSnapshotContentName:
                  type: string
                creationTime:
                  type: string
                readyToUse:
                  type: boolean
                restoreSize:
                  type: string
                error:
                  type: object
                  properties:
                    message:
                      type: string
                    time:
                      type: string
  scope: Namespaced
  names:
    plural: volumesnapshots
    singular: volumesnapshot
    kind: VolumeSnapshot
    shortNames:
      - volumesnapshot
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotcontents.snapshot.storage.k8s.io
spec:
  group: snapshot.storage.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                volumeSnapshotRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                volumeSnapshotClassName:
                  type: string
                sourceVolumeMode:
                  type: string
                sourceFilesystemType:
                  type: string
                volumeHandle:
                  type: string
                deletionPolicy:
                  type: string
                driver:
                  type: string
                readonly:
                  type: boolean
                volumeContext:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                creationTime:
                  type: string
                readyToUse:
                  type: boolean
                restoreSize:
                  type: string
                error:
                  type: object
                  properties:
                    message:
                      type: string
                    time:
                      type: string
  scope: Cluster
  names:
    plural: volumesnapshotcontents
    singular: volumesnapshotcontent
    kind: VolumeSnapshotContent
    shortNames:
      - volumesnapshotcontent
