apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-attacher
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-attacher
  template:
    metadata:
      labels:
        app: csi-attacher
    spec:
      tolerations:
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 600
      containers:
      - name: csi-attacher
        image: registry.k8s.io/sig-storage/csi-attacher:v3.5.0
        args:
        - --v=5
        - --provisioner=example.com/csi
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/kubelet/plugins/
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/
          type: DirectoryOrCreate
