apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
data:
  # NOTE: Replace placeholder values with actual configuration required by the Minecraft Bedrock server.
  # Obtain correct values from secure secret management or application documentation.
  username: bXlnY3JlYXRlcg==
  password: bXlcMjRzZWN1cml0eQ==
