apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-repo-health-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-repo-health-exporter
  template:
    metadata:
      labels:
        app: github-repo-health-exporter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: exporter
          image: jdwlabs/github-repo-health-exporter:0.0.1@sha256:3f697eefb82e9cd1266efee0ba13e32f82bcc9a1956c08cb1d51e31f670b33c4
          ports:
            - containerPort: 8080
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
