apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildx-builder
  namespace: jdwlabs-runners
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
