apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
stringData:
  console_websocket_password: "CHANGE_ME"
  console_bridge_token: "CHANGE_ME"
