apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-driver-config
  namespace: democratic-csi
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: democratic-csi-driver-config
    template:
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nfs
          httpConnection:
            protocol: http
            host: 192.168.1.205
            port: 80
            apiKey: "{{ .api_key }}"
          zfs:
            datasetParentName: storage/k8s/vols
            detachedSnapshotsDatasetParentName: storage/k8s/snaps
            datasetEnableQuotas: true
            datasetEnableReservation: false
          nfs:
            shareHost: 192.168.1.205
            shareAlldirs: false
            shareAllowedNetworks:
              - 192.168.1.0/24
            shareMaprootUser: root
            shareMaprootGroup: root
  data:
    - secretKey: api_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: truenas-csi
        property: api_key
