apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dotablaze-tech-github-app
  namespace: dotablaze-tech-runners
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dotablaze-tech-github-app
  data:
    - secretKey: github_app_id
      remoteRef:
        key: dotablaze-tech-github-app
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: dotablaze-tech-github-app
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: dotablaze-tech-github-app
        property: github_app_private_key
