apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
 type: Opaque
stringData:
  console_websocket_password: "PLACEHOLDER_WEBSOCKET_PASSWORD"
  console_bridge_token: "PLACEHOLDER_BRIDGE_TOKEN"
