apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
stringData:
  console_websocket_password: "PUT_REAL_PASSWORD_HERE"
  console_bridge_token: "PUT_REAL_TOKEN_HERE"
