apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-operator-metrics
  namespace: cnpg-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  namespaceSelector:
    matchNames:
      - cnpg-system
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
