# cluster:
#  storage:
#    size: 2Gi
#    storageClass: "openebs-single-replica"

externalClusters: []

cluster:
  monitoring:
    enablePodMonitor: true

  initdb:
    postInitSQL:
      - ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO app;
      - ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO app;
      - ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO app;
      - ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO app;

  roles:
    - name: jdwlabs_non_owner
      ensure: present
      login: true
      inherit: true
      connectionLimit: -1
      comment: "Owner of jdwlabs_non database"
      passwordSecret:
        name: jdwlabs-non-owner-credentials

    - name: dotablazetech_non_owner
      ensure: present
      login: true
      inherit: true
      connectionLimit: -1
      comment: "Owner of dotablazetech_non database"
      passwordSecret:
        name: dotablazetech-non-owner-credentials

    - name: app
      ensure: present
      login: true
      inherit: true
      connectionLimit: -1
      comment: "Application user with inherited access to all tenant databases"
      inRoles:
        - jdwlabs_non_owner
        - dotablazetech_non_owner

databases:
  - name: jdwlabs_non
    ensure: present
    owner: jdwlabs_non_owner
    schemas:
      - name: auth
        owner: jdwlabs_non_owner
        ensure: present
  - name: dotablazetech_non
    ensure: present
    owner: dotablazetech_non_owner
