apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
stringData:
  # TODO: Replace placeholder values with actual secret data
  # Example:
  # username: admin
  # password: changeme
