apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
data:
  # Placeholder values; replace with actual secret data as needed
  username: ""
  password: ""
