apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-gitsync-github-app
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-gitsync-github-app
  data:
    - secretKey: app-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana-gitsync
        property: app-id
    - secretKey: installation-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana-gitsync
        property: installation-id
    - secretKey: private-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana-gitsync
        property: private-key
