#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — registers the jdwlabs-agent-bot GitHub App (docs/adr/0017), installs
# it on all four jdwlabs repos, and wires per-repo AGENT_APP_ID /
# AGENT_APP_PRIVATE_KEY secrets via gh, mirroring the RELEASE_APP_ID /
# RELEASE_APP_PRIVATE_KEY pattern already live in
# deployments/.github/workflows/promote-prd.yml.
#
# Everything through App registration and key generation is a GitHub-UI-only
# action; no agent or API call can do it. The secret-wiring stage is the only
# part this script can execute unattended, and only because gh is already
# authenticated with org-admin rights when this is run.
# ──────────────────────────────────────────────────────────────────────────

ORG="jdwlabs"
REPOS=(apps platform infrastructure deployments)

# Keep the local record out of any repo working tree — this file ends up
# holding the App ID and a path to the private key (never the key material
# itself), but there's no reason for it to live inside a git-tracked dir.
# Plain assignment, not "${ENV_FILE:-...}": the library above the marker
# already defaults ENV_FILE to ".env", so a second :- here would never fire
# and this script would silently write into the repo's cwd instead.
ENV_FILE="$HOME/.config/jdwlabs/agent-app-identity.env"
mkdir -p "$(dirname "$ENV_FILE")"

TOTAL_STAGES=5

banner "jdwlabs-agent-bot — GitHub App setup"

# ── Stage 1: register the App ──────────────────────────────────────────────
stage "Register the App"
say "Creating the shared agentic-contribution identity decided in docs/adr/0017."
say "Distinct from jdwlabs-release-bot (release promotion) and jdwlabs-grafana-gitsync (dashboard sync) — this one is for agent-authored PRs across all four repos."
open_url "https://github.com/organizations/${ORG}/settings/apps/new"
step "GitHub App name: jdwlabs-agent-bot (rename here if that slug is taken)."
step "Homepage URL: https://github.com/${ORG} (placeholder — no webhook, no callback needed)."
step "Webhook: uncheck 'Active' — this App never receives events, it only mints tokens."
step "Repository permissions → Contents: Read and write."
step "Repository permissions → Pull requests: Read and write."
step "Leave every other permission at 'No access'. Metadata: Read-only is added automatically."
step "'Where can this GitHub App be installed?' → Only on this account."
step "Click 'Create GitHub App'."
say "On the App's settings page that opens next, copy the App ID shown near the top."
ask AGENT_APP_ID "Paste the App ID:"
write_env AGENT_APP_ID "$AGENT_APP_ID"
say "Also copy the slug from the page's URL (github.com/organizations/${ORG}/settings/apps/<slug>) —"
say "needed below even if you kept the default name, and required if that name was taken."
ask AGENT_APP_SLUG "App slug (Enter for jdwlabs-agent-bot):"
AGENT_APP_SLUG="${AGENT_APP_SLUG:-jdwlabs-agent-bot}"
write_env AGENT_APP_SLUG "$AGENT_APP_SLUG"

# ── Stage 2: generate + save the private key ───────────────────────────────
stage "Generate the private key"
say "Still on the App's settings page (scroll to 'Private keys')."
step "Click 'Generate a private key' — this downloads a .pem file once; GitHub does not keep a copy."
step "Move it somewhere durable outside any git working tree, e.g. ~/.config/jdwlabs/jdwlabs-agent-bot.pem."
warn "Never commit this file. It is the App's full write credential across every repo it's installed on."
ask AGENT_PRIVATE_KEY_PATH "Full path to the saved .pem file:"
if [[ ! -f "$AGENT_PRIVATE_KEY_PATH" ]]; then
  warn "no file found at that path — you can re-run this script once it's saved; nothing was lost."
  SKIPPED+=("private key file not found at $AGENT_PRIVATE_KEY_PATH — re-run to continue")
else
  write_env AGENT_PRIVATE_KEY_PATH "$AGENT_PRIVATE_KEY_PATH"
  note "recorded the path only — the key content itself is never written to $ENV_FILE"
fi

# ── Stage 3: install on the four repos ──────────────────────────────────────
stage "Install on the four repos"
say "docs/adr/0017 §2 deliberately scopes this narrower than jdwlabs-release-bot's org-wide install."
if [[ -z "${AGENT_APP_SLUG:-}" ]]; then
  AGENT_APP_SLUG=$(_existing AGENT_APP_SLUG || echo jdwlabs-agent-bot)
fi
open_url "https://github.com/organizations/${ORG}/settings/apps/${AGENT_APP_SLUG}/installations"
step "Click 'Install' (or the gear icon if already installed once)."
step "Choose 'Only select repositories'."
for r in "${REPOS[@]}"; do
  step "Select ${ORG}/${r}"
done
step "Save the installation."
confirm "Installed on exactly apps, platform, infrastructure, deployments — no others?" \
  || warn "double-check the installation's repository list before continuing — extra repos widen the App's write access unnecessarily"

# ── Stage 4: wire secrets on all four repos ─────────────────────────────────
stage "Wire per-repo secrets"
say "Setting AGENT_APP_ID and AGENT_APP_PRIVATE_KEY on each repo via gh — this part runs unattended."
if [[ -z "${AGENT_APP_ID:-}" ]]; then
  AGENT_APP_ID=$(_existing AGENT_APP_ID || true)
fi
if [[ -z "${AGENT_PRIVATE_KEY_PATH:-}" ]]; then
  AGENT_PRIVATE_KEY_PATH=$(_existing AGENT_PRIVATE_KEY_PATH || true)
fi
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh is not ready — set these by hand once it is:"
  for r in "${REPOS[@]}"; do
    SKIPPED+=("gh secret set AGENT_APP_ID --repo ${ORG}/${r} --body <app-id>")
    SKIPPED+=("gh secret set AGENT_APP_PRIVATE_KEY --repo ${ORG}/${r} < <pem-path>")
  done
elif [[ -z "${AGENT_APP_ID:-}" || -z "${AGENT_PRIVATE_KEY_PATH:-}" || ! -f "${AGENT_PRIVATE_KEY_PATH:-/nonexistent}" ]]; then
  warn "App ID or private key path missing — re-run this script after completing stages 1-2."
else
  for r in "${REPOS[@]}"; do
    target="${ORG}/${r}"
    if printf '%s' "$AGENT_APP_ID" | gh secret set AGENT_APP_ID --repo "$target" >/dev/null 2>&1; then
      printf '  %s✓ set%s AGENT_APP_ID on %s\n' "$GREEN" "$RESET" "$target"
    else
      SKIPPED+=("AGENT_APP_ID on $target")
      warn "failed to set AGENT_APP_ID on $target"
    fi
    if gh secret set AGENT_APP_PRIVATE_KEY --repo "$target" < "$AGENT_PRIVATE_KEY_PATH" >/dev/null 2>&1; then
      printf '  %s✓ set%s AGENT_APP_PRIVATE_KEY on %s\n' "$GREEN" "$RESET" "$target"
    else
      SKIPPED+=("AGENT_APP_PRIVATE_KEY on $target")
      warn "failed to set AGENT_APP_PRIVATE_KEY on $target"
    fi
  done
fi

# ── Stage 5: verify ──────────────────────────────────────────────────────────
stage "Verify"
say "Confirms the secrets landed. Minting an actual installation token needs a workflow"
say "run (the create-github-app-token step drafted in docs/adr/0017 §4) — not something"
say "this script can trigger before that workflow step exists."
for r in "${REPOS[@]}"; do
  target="${ORG}/${r}"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    # grep exits 1 (no match) on the very first-run/no-secrets-yet case this
    # stage exists to catch — under `set -o pipefail` that would kill the
    # whole script here instead of reaching the warn branch below.
    names=$(gh secret list --repo "$target" --json name -q '.[].name' 2>/dev/null | { grep -E '^AGENT_APP_(ID|PRIVATE_KEY)$' || true; } | sort | tr '\n' ' ')
    if [[ "$names" == "AGENT_APP_ID AGENT_APP_PRIVATE_KEY " ]]; then
      printf '  %s✓%s %s has both secrets\n' "$GREEN" "$RESET" "$target"
    else
      warn "$target is missing one or both secrets (found: ${names:-none})"
    fi
  fi
done
note "Next (separate PR, not this script): add actions/create-github-app-token to the"
note "workflow that opens agent-authored PRs, keyed on AGENT_APP_ID / AGENT_APP_PRIVATE_KEY —"
note "see docs/adr/0018-agentic-app-topology.md §4 for the exact shape to mirror from"
note "deployments/.github/workflows/promote-prd.yml."

finish
