installCRDs: true

extraArgs:
  - --enable-gateway-api
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53

# webhook:
#  limits:
#    ephemeral-storage: 500Mi

# cainjector:
#  enabled: false

startupapicheck:
  enabled: false
#  limits:
#    ephemeral-storage: 500Mi

# resources:
#  limits:
#    ephemeral-storage: 500Mi
