apiVersion: v1
kind: Service
metadata:
  name: truenas-prometheus-exporter
  namespace: monitoring
  labels:
    app: truenas-prometheus-exporter
spec:
  type: ClusterIP
  selector:
    app: truenas-prometheus-exporter
  ports:
    - name: metrics
      port: 9124
      targetPort: metrics
      protocol: TCP
