cluster:
  name: jdwlabs
  namespace: monitoring

clusterMetrics:
  enabled: true
  # Do not deploy - kube-prometheus-stack owns these
  node-exporter:
    deploy: false
    enabled: false
  kube-state-metrics:
    deploy: false
    enabled: false

clusterEvents:
  enabled: true

podLogs:
  enabled: true

nodeLogs:
  enabled: true

alloy-logs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

destinations:
  - name: Loki
    type: loki
    url: "http://platform-loki:3100/loki/api/v1/push"
  - name: Prometheus
    type: prometheus
    url: "http://platform-kube-prometheus-stack-prometheus:9090/api/v1/write"
