apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-basic-auth
  namespace: nginx-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: longhorn-basic-auth
  data:
    - secretKey: auth
      remoteRef:
        key: longhorn
        property: htpasswd_string
