tenant: jdwlabs
apps:
  - name: arc-runner-set-jdwlabs
    tenant: jdwlabs
    chart: gha-runner-scale-set
    repo: ghcr.io/actions/actions-runner-controller-charts
    revision: 0.13.1
    namespace: jdwlabs-runners
    postInstall: true
    syncWave: 5

  - name: arc-runner-set-jdwlabs-custom
    tenant: jdwlabs
    chart: gha-runner-scale-set
    repo: ghcr.io/actions/actions-runner-controller-charts
    revision: 0.13.1
    namespace: jdwlabs-runners
    postInstall: false
    syncWave: 5

  - name: jdwlabs-schemas
    tenant: jdwlabs
    chart: cluster
    repo: https://cloudnative-pg.github.io/charts
    revision: 0.4.0
    namespace: database
    postInstall: true
    syncWave: 5
