apiVersion: v1
kind: Secret
metadata:
  name: minecraft-fwb-console-bridge
  namespace: jdwillmsen-prd
type: Opaque
stringData:
  # Placeholder values; replace with actual secret data as needed
  username: "placeholder"
  password: "placeholder"