apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dex-secrets
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: admin-password-hash
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-dex
        property: admin-password-hash
    - secretKey: headlamp-client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-dex
        property: headlamp-client-secret
    - secretKey: github-client-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-dex
        property: github-client-id
    - secretKey: github-client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-dex
        property: github-client-secret
    - secretKey: google-client-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-dex
        property: google-client-id
    - secretKey: google-client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: argocd-dex
        property: google-client-secret
