apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jdwillmsen-deployments-repo
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: jdwillmsen-deployments-repo
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/jdwillmsen/deployments-private
        githubAppID: "{{ .app_id }}"
        githubAppInstallationID: "{{ .installation_id }}"
        githubAppPrivateKey: "{{ .private_key }}"
  data:
    - secretKey: app_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: jdwillmsen-argocd-repo
        property: app-id
    - secretKey: installation_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: jdwillmsen-argocd-repo
        property: installation-id
    - secretKey: private_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: jdwillmsen-argocd-repo
        property: private-key
