name: Release Chart

on:
  push:
    tags:
      - '*-v[0-9]*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    uses: jdwlabs/.github/.github/workflows/release-helm.yml@main
    permissions:
      contents: write
      pages: write
    with:
      charts-dir: helm-charts
      pages-url: https://jdwlabs.github.io/platform
